"use client";
import { useState, useRef, useEffect } from "react";

const ITEMS = [
  {
    title: "The fiber-level record",
    desc: "Every product gets a complete Digital Product Passport: origin, carbon footprint, recyclability and REACH compliance — generated by default, not in a spreadsheet.",
    visual: "dpp" as const,
  },
  {
    title: "Public passport via QR and NFC",
    desc: "Direct export to QR, NFC and GS1 Digital Link. The consumer reads the product's story; the customer and auditor reach the same immutable record.",
    visual: "lots" as const,
  },
  {
    title: "Wired to your shop floor",
    desc: "TextileEco sits on top of the Hestia textile ERP: lots, looms and orders feed the passport automatically — no double data entry.",
    visual: "floor" as const,
  },
  {
    title: "AI for data and compliance",
    desc: "Models trained on European textile data fill gaps, validate supplier declarations and flag non-conformities before the audit.",
    visual: "ai" as const,
  },
];

function ShopFloorVisual() {
  const statusMap: Record<string, [string, string]> = {
    running: ["#118D57", "#E6F4EC"],
    error: ["#B42318", "#FBE9E7"],
    hold: ["#6941C6", "#EDE9FB"],
    maintenance: ["#475467", "#EAECF0"],
  };

  return (
    <div style={{ width: "100%", padding: 28, display: "flex", flexDirection: "column", gap: 12 }}>
      <div style={{ display: "flex", justifyContent: "space-between", alignItems: "center" }}>
        <div>
          <div style={{ fontSize: 11, fontWeight: 600, color: "var(--muted-foreground)", letterSpacing: "0.1em", textTransform: "uppercase" }}>Line 2 · Weaving</div>
          <div style={{ fontFamily: "'Geist Mono', monospace", fontSize: 13, color: "var(--muted-foreground)" }}>18 looms · 6 operators</div>
        </div>
        <span style={{ display: "inline-flex", alignItems: "center", gap: 6, padding: "4px 10px", borderRadius: 9999, fontSize: 12.5, fontWeight: 600, color: "#118D57", background: "#E6F4EC", border: "1px solid #B5DBC5" }}>14 running</span>
      </div>
      <div style={{ display: "grid", gridTemplateColumns: "repeat(6, 1fr)", gap: 8 }}>
        {Array.from({ length: 18 }).map((_, i) => {
          const status = i === 4 ? "error" : i === 9 ? "hold" : i === 13 ? "maintenance" : "running";
          const [fg, bg] = statusMap[status];
          return (
            <div key={i} style={{ background: bg, color: fg, border: `1px solid ${fg}33`, borderRadius: 8, padding: "10px 8px", textAlign: "center" }}>
              <svg width={20} height={20} viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                <use href="/textile-icons.svg#loom" />
              </svg>
              <div style={{ fontFamily: "'Geist Mono', monospace", fontSize: 10, marginTop: 4 }}>L-{String(i + 1).padStart(3, "0")}</div>
            </div>
          );
        })}
      </div>
      <div style={{ marginTop: 8, padding: 16, background: "var(--background)", borderRadius: 12, border: "1px solid var(--border)" }}>
        <div style={{ display: "flex", justifyContent: "space-between", marginBottom: 8 }}>
          <div style={{ fontSize: 12, fontWeight: 600, letterSpacing: "0.08em", textTransform: "uppercase", color: "var(--muted-foreground)" }}>OEE Line 2 · 24h</div>
          <div style={{ fontFamily: "'Geist Mono', monospace", fontSize: 13, color: "#118D57" }}>↑ 84.3%</div>
        </div>
        <svg viewBox="0 0 300 60" width="100%" height="60">
          <path d="M0,40 Q30,30 60,32 T120,28 T180,18 T240,22 T300,12" stroke="#003DA5" strokeWidth="2" fill="none" />
          <path d="M0,40 Q30,30 60,32 T120,28 T180,18 T240,22 T300,12 L300,60 L0,60 Z" fill="#003DA5" opacity="0.08" />
        </svg>
      </div>
    </div>
  );
}

function LotsVisual() {
  const lots = [
    { id: "2A-0094", customer: "Burberry SS27", color: "#B89968", state: "running", gsm: 220 },
    { id: "2A-0091", customer: "Lacoste FW26", color: "#003DA5", state: "running", gsm: 180 },
    { id: "2A-0102", customer: "Decathlon", color: "#118D57", state: "hold", gsm: 240 },
    { id: "2A-0089", customer: "Salsa", color: "#475467", state: "running", gsm: 200 },
    { id: "2A-0078", customer: "Inditex", color: "#C2410C", state: "running", gsm: 160 },
  ];
  return (
    <div style={{ width: "100%", padding: 28, display: "flex", flexDirection: "column", gap: 8 }}>
      <div style={{ fontSize: 11, fontWeight: 600, letterSpacing: "0.1em", textTransform: "uppercase", color: "var(--muted-foreground)", marginBottom: 8 }}>Active lots</div>
      {lots.map((l) => (
        <div key={l.id} style={{ display: "grid", gridTemplateColumns: "32px 1fr auto auto", gap: 12, alignItems: "center", padding: "12px 14px", background: "var(--background)", border: "1px solid var(--border)", borderRadius: 10 }}>
          <div style={{ width: 28, height: 28, borderRadius: 6, background: l.color }} />
          <div>
            <div style={{ fontSize: 14, fontWeight: 500 }}>{l.customer}</div>
            <div style={{ fontFamily: "'Geist Mono', monospace", fontSize: 11, color: "var(--muted-foreground)" }}>Lot {l.id} · {l.gsm} g/m²</div>
          </div>
          <div style={{ fontFamily: "'Geist Mono', monospace", fontSize: 12, color: "var(--muted-foreground)" }}>08/24</div>
          <span style={{
            display: "inline-flex", alignItems: "center", gap: 6, padding: "4px 10px", borderRadius: 9999, fontSize: 12.5, fontWeight: 600,
            color: l.state === "running" ? "#118D57" : "#6941C6",
            background: l.state === "running" ? "#E6F4EC" : "#EDE9FB",
            border: `1px solid ${l.state === "running" ? "#B5DBC5" : "#CFC2F1"}`,
          }}>
            {l.state === "running" ? "Running" : "QC Hold"}
          </span>
        </div>
      ))}
    </div>
  );
}

function DppVisual() {
  const rows = [
    { l: "Fiber origin", v: "BCI Cotton · Turkey" },
    { l: "CO₂ footprint", v: "4.2 kg eq/kg" },
    { l: "Recyclability", v: "Class A · 92%" },
    { l: "Substances", v: "REACH ✓ · ZDHC ✓" },
  ];
  return (
    <div style={{ width: "100%", padding: 28, display: "flex", alignItems: "center", justifyContent: "center", flexDirection: "column" }}>
      <div style={{ position: "relative", padding: 24, background: "var(--background)", borderRadius: 16, border: "1px solid var(--border)" }}>
        <img src="/dpp-seal.svg" alt="DPP" style={{ width: 140, height: 140, display: "block" }} />
      </div>
      <div style={{ marginTop: 16, fontFamily: "'Geist Mono', monospace", fontSize: 11, letterSpacing: "0.08em", textTransform: "uppercase", color: "var(--ember)", fontWeight: 700 }}>DPP READY · LOT 2A-0094</div>
      <div style={{ marginTop: 24, display: "flex", flexDirection: "column", gap: 8, width: "100%", maxWidth: 360 }}>
        {rows.map((r, i) => (
          <div key={i} style={{ display: "flex", justifyContent: "space-between", padding: "8px 12px", borderRadius: 8, background: "var(--background)", border: "1px solid var(--border)", fontSize: 13 }}>
            <span style={{ color: "var(--muted-foreground)" }}>{r.l}</span>
            <span style={{ fontWeight: 500 }}>{r.v}</span>
          </div>
        ))}
      </div>
    </div>
  );
}

function AiVisual() {
  return (
    <div style={{ width: "100%", padding: 28 }}>
      <div style={{ background: "var(--background)", border: "1px solid var(--border)", borderRadius: 12, padding: 20, marginBottom: 12 }}>
        <div style={{ fontSize: 11, fontWeight: 600, letterSpacing: "0.1em", textTransform: "uppercase", color: "var(--muted-foreground)", marginBottom: 8 }}>Hestia Assistant</div>
        <div style={{ fontSize: 15, lineHeight: 1.5 }}>
          <span style={{ color: "var(--muted-foreground)" }}>"When does lot </span>
          <span style={{ fontFamily: "'Geist Mono', monospace", color: "var(--primary)" }}>2A-0094</span>
          <span style={{ color: "var(--muted-foreground)" }}> finish?"</span>
        </div>
      </div>
      <div style={{ background: "var(--ember-tint)", border: "1px solid var(--ember-soft)", borderRadius: 12, padding: 20 }}>
        <div style={{ fontSize: 11, fontWeight: 700, letterSpacing: "0.1em", textTransform: "uppercase", color: "var(--ember)", marginBottom: 8 }}>Forecast · 92% confidence</div>
        <div style={{ fontSize: 15, lineHeight: 1.55 }}>
          Estimated completion <strong>Thursday, 14:20</strong>. Running 38min behind plan due to L-019 stoppage (10:42). Recommend redistributing 320m to L-022.
        </div>
      </div>
      <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: 8, marginTop: 12 }}>
        {[
          { k: "Defects detected", v: "3", c: "#B42318" },
          { k: "Load optimization", v: "+4.8%", c: "#118D57" },
        ].map((m, i) => (
          <div key={i} style={{ background: "var(--background)", border: "1px solid var(--border)", borderRadius: 10, padding: "12px 14px" }}>
            <div style={{ fontSize: 11, fontWeight: 600, letterSpacing: "0.06em", textTransform: "uppercase", color: "var(--muted-foreground)" }}>{m.k}</div>
            <div style={{ fontSize: 22, fontWeight: 600, color: m.c, marginTop: 4 }}>{m.v}</div>
          </div>
        ))}
      </div>
    </div>
  );
}

export default function FeatureShowcaseHomeEn() {
  const [active, setActive] = useState(0);
  const refs = useRef<(HTMLDivElement | null)[]>([]);

  useEffect(() => {
    const obs = new IntersectionObserver(
      (entries) => {
        entries.forEach((e) => {
          if (e.isIntersecting) {
            const idx = Number((e.target as HTMLElement).dataset.idx);
            setActive(idx);
          }
        });
      },
      { rootMargin: "-40% 0px -40% 0px", threshold: 0 }
    );
    refs.current.forEach((el) => el && obs.observe(el));
    return () => obs.disconnect();
  }, []);

  const visuals = { floor: <ShopFloorVisual />, lots: <LotsVisual />, dpp: <DppVisual />, ai: <AiVisual /> };

  return (
    <section style={{ padding: "clamp(80px, 10vw, 128px) 0", background: "var(--muted)", borderTop: "1px solid var(--border)", borderBottom: "1px solid var(--border)" }}>
      <div style={{ maxWidth: 1200, margin: "0 auto", padding: "0 24px" }}>
        <div style={{ maxWidth: 720, marginBottom: 56, marginLeft: "auto", marginRight: "auto", textAlign: "center" }}>
          <div style={{ display: "inline-flex", alignItems: "center", gap: 12, marginBottom: 20 }}>
            <span style={{ width: 28, height: 1, background: "var(--primary)", display: "inline-block", opacity: 0.55 }} />
            <span style={{ fontSize: 12, fontWeight: 700, letterSpacing: "0.18em", textTransform: "uppercase", color: "var(--primary)" }}>Platform</span>
            <span style={{ width: 28, height: 1, background: "var(--primary)", display: "inline-block", opacity: 0.55 }} />
          </div>
          <h2 style={{ fontSize: "clamp(2rem, 3.5vw, 3rem)", fontWeight: 700, lineHeight: 1.1, letterSpacing: "-0.03em" }}>
Everything the Digital Product Passport demands.<br />In one record.
          </h2>
        </div>

        <div style={{ display: "grid", gridTemplateColumns: "1fr 1.2fr", gap: 64, alignItems: "start" }} className="showcase-grid">
          <div>
            {ITEMS.map((item, i) => (
              <div
                key={i}
                ref={(el) => { refs.current[i] = el; }}
                data-idx={i}
                onClick={() => setActive(i)}
                style={{
                  padding: "20px 0",
                  borderTop: "1px solid var(--border)",
                  borderBottom: i === ITEMS.length - 1 ? "1px solid var(--border)" : undefined,
                  cursor: "pointer",
                  position: "relative",
                  paddingLeft: 16,
                }}
              >
                {active === i && (
                  <span style={{ position: "absolute", left: 0, top: 28, width: 6, height: 6, background: "var(--ember)", borderRadius: 999 }} />
                )}
                <h3 style={{
                  fontSize: 22,
                  fontWeight: 600,
                  letterSpacing: "-0.02em",
                  marginBottom: 8,
                  color: active === i ? "var(--foreground)" : "var(--muted-foreground)",
                  transition: "color 200ms ease",
                }}>
                  {item.title}
                </h3>
                <p style={{
                  fontSize: 15,
                  lineHeight: 1.6,
                  color: "var(--muted-foreground)",
                  maxHeight: active === i ? 200 : 0,
                  overflow: "hidden",
                  opacity: active === i ? 1 : 0,
                  marginTop: active === i ? 4 : 0,
                  transition: "max-height 400ms cubic-bezier(0.16,1,0.3,1), opacity 250ms ease, margin 300ms ease",
                }}>
                  {item.desc}
                </p>
              </div>
            ))}
          </div>

          <div style={{ position: "sticky", top: 96 }}>
            <div style={{
              background: "var(--card)",
              border: "1px solid var(--border)",
              borderRadius: 18,
              aspectRatio: "4/3",
              overflow: "hidden",
              boxShadow: "var(--shadow-md)",
              position: "relative",
            }}>
              {ITEMS.map((item, i) => (
                <div
                  key={i}
                  style={{
                    position: "absolute",
                    inset: 0,
                    opacity: active === i ? 1 : 0,
                    transition: "opacity 300ms ease",
                    display: "flex",
                    overflowY: "auto",
                  }}
                >
                  {visuals[item.visual]}
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>

      <style>{`
        @media (max-width: 980px) {
          .showcase-grid { grid-template-columns: 1fr !important; }
          .showcase-grid > div:last-child { position: static !important; }
        }
      `}</style>
    </section>
  );
}
